### ISSUE TITLE
Proposal: Enrich `draft info` with variable defaults

### ISSUE THREAD

**Issue by davidgamero** [Azure/draft#164]
**Is your feature request related to a problem? Please describe.**
When consuming draft as a wrapped binary, the available variable defaults for VERSION and BUILDERVERSION are not exposed non-interactively. Exposing these in the `info` command would make draft more extensible in this pattern.

This would be particularly useful for the [aks-devx-tools](https://github.com/Azure/aks-devx-tools) vscode extension since it is pioneering our binary consumption pattern

The goal of this PR is to remove the need for static files like [languages.ts](https://github.com/Azure/aks-devx-tools/blob/f5398dd004bad018a3b490b8022113440249c603/src/commands/runDraftTool/helper/languages.ts) that are sensitive to becoming out-of-date with each incremental draft version, and would require significant extra work to keep in sync with 3rd party draft templates.

Exposing the following information would make the draft binary more extensible:
- Default values for BuilderVariables in the draft.yaml
- A formatted/capitalized display name for a selected language/deployType/addon

**Mention what platform you want to support the new feature**
Mention what platform you would like the feature request to live in (az-extension, oss draft, vscode) and select the proper label.

**Describe the solution you'd like**

### Draft info output
The current `info` command prints the following format in stdout:
```json
{
  "supported_languages": [
    "javascript",
    ...
  ],
 "supported_deployment_types": [
    "helm",
    ...
  ]
}
```

I propose enriching this information with the following additional sub fields for each language:
```json
{
  "supported_languages": [
    {
      "name": "javascript"
      "display_name": "JavaScript",
      "exampleValues": {
        "VERSION": [
          "14.0",
          "16.0"
        ]
      }
    }
    ..
  ],
 "supported_deployment_types": [
    {
      "name": "helm"
      "display_name": "Helm",
      "exampleValues": {
        "PORT" : "80"
      }
    }
    ..
  ]
}
```

### draft.yml format changes
In order to better support standardized consumption, I propose changing the `value` field on the `variableDefault` type from a string to an array of strings. For the CLI, the first default in the array would be used, but allowing additional defaults can be echoed in the info command to provide examples (ex: providing several recommended versions for a language dockerfile).
```yaml
# Current abbreviated example for a language draft.yaml
language: swift
variables:
  - name: "VERSION"
    description: "the version of swift used by the application"
variableDefaults:
  - name: "VERSION"
    value: 5.5


# Proposed abbreviated changes for a language draft.yaml
language: swift
displayName: Swift # Add a display name for the selected resource (language/deploymentType/addon)
variables:
  - name: "VERSION"
    description: "the version of swift used by the application"
    exampleValues: ["5.5","5.4"] # New field

variableDefaults:
  - name: "VERSION"
     value: "5.5"
```

**Describe alternatives you've considered**
Alternatives include parsing the raw draft templates in their yaml formats, or creating a second source of truth for this information.

Since one of the core value-adds of draft is its single-binary install that leverages embedded file systems and its focus on extensibility, these alternatives are less in line with the overall project vision.

**Additional context**

update integration-info test to ensure our json output maintains a strong contract
