### ISSUE TITLE
[Ubuntu 16.04 LTS]: draft connect hangs

### ISSUE THREAD

**Issue by squillace** [Azure/draft#612]
![image](https://user-images.githubusercontent.com/1422718/37942025-0093e9a0-3126-11e8-8c27-1d6df4e7f8b6.png)

Might be related to the sudo issue #611.

**Comment by radu-matei** [comment]
Do you have the latest version of the packs?
The error there happens when the client doesn't find a pod with that annotation - and this happens if the template doesn't contain the annotation.

**Comment by squillace** [comment]
Dunno. to use it, I `rm -rf ~/.draft`, which I assume torched the older packs. if not, I need to know how to do that. :-)

**Comment by radu-matei** [comment]
That should have done the trick.
Could you `cat charts/templates/deployment.yaml`?

**Comment by squillace** [comment]
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
```

**Comment by radu-matei** [comment]
Yup, you don't have the latest version of the pack - either recreate the app (delete stuff and `draft create` again) or update your `deployment.yaml` to be:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
``` 

This most likely happened because you had an existing application created before upgrading - and we must document this somewhere.
