### ISSUE TITLE
Overriding '.Values.image.tag' during draft up

### ISSUE THREAD

**Issue by Joeskyyy** [Azure/draft#635]
Hey there!

I'm having issues overriding the `.Values.image.tag` attribute during a draft up. Our use case is that we'd like to set custom tags during a build (In this case a commit ID). When trying to set the value in `values.yml` it seems like draft arbitrarily picks a SHA for this value.

For example:

```
# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
  repository: my-awesome-repo.corp/foo
  tag: "abcd123"
service:
  name: java
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
ingress:
  enabled: false
```

This works fine with `helm install` I should note.

Digging a bit, it seems like the context ID of the build looks to be used to construct a checksum of the build as the tag? https://github.com/Azure/draft/blob/c7c7d08721328cf84a792b23affb1476080f510e/pkg/builder/builder.go#L84

Is there any way to have draft handle this?
