### ISSUE TITLE
draft.toml's `set` parameters are not being loaded into the Helm chart.

### ISSUE THREAD

**Issue by technosophos** [Azure/draft#660]
I specified:

```toml
[environments.development]
set = ["foo=bar"]
```

When I `draft up` and then `helm get values`, I do not see `foo` there.
