### ISSUE TITLE
Issue with Python example

### ISSUE THREAD

**Issue by jackzampolin** [Azure/draft#91]
I was going through the [getting started example](https://github.com/Azure/draft/blob/master/docs/getting-started.md) and ran into a roadblock. My app was deploying just fine (super cool piece of software btw! I've been doing this by `helm create`) but it wasn't hooking into my ingress controller. Looking in the `python/chart/ingress.yaml` it looked like the annotation to allow my ingress controller to pick it up was missing:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
...
```
I went ahead and added it and after starting over with the tutorial I was able to get it working. Should I open a PR to add this annotation to the different packs by default?
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
```
